FROM jupyter/base-notebook@sha256:8635b39569cddecf2fac3d95ffe7777d007153e46d47a5dc873357d7cb2d5478

LABEL organization="Alaska Satellite Facility"
LABEL author="Alex Lewandowski, Rui Kawahara, & Eric Lundell"
LABEL creation_date="2022-05-26"

# Base Stage ****************************************************************
USER root

RUN set -ve

RUN apt update && \
    apt install --no-install-recommends -y \
        software-properties-common \
        git && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt update && \
    apt upgrade -y

RUN apt update && \
    apt install --no-install-recommends -y \
        zip \
        unzip \
        wget \
        vim \
        rsync \
        less \
        snaphu \
        curl \
        openssh-client \
        libgl1-mesa-glx \
        emacs \
        gnupg2 \
        jq \
        gfortran \
        proj-bin \
        geotiff-bin \
        libshp-dev \
        libshp2 \
        libhdf5-dev \
        libnetcdf-dev \
        libgdal-dev \
        libgsl-dev

ENV INVERSE_FILES /etc/inverse

RUN conda install conda=4.12.0 && \
    conda update -n base mamba

RUN mkdir $INVERSE_FILES && \
    chmod -R 777 /etc/inverse/

RUN mamba install -c conda-forge jupyter_contrib_nbextensions \
        jupyter_nbextensions_configurator \
        jupyter-resource-usage \
        conda-pack \
        kernda \
        nb_conda_kernels \
        mamba_gator

# Make sure mamba (within conda) has write access
RUN conda clean --yes --all && \
    chmod -R 777 /opt/conda/pkgs/

# Copy essential files from this directory to docker image
COPY etc/pull.py ${INVERSE_FILES}/pull.py
COPY etc/startup.sh ${INVERSE_FILES}/startup.sh

USER jovyan

EXPOSE 8888

ENTRYPOINT bash ${INVERSE_FILES}/startup.sh; jupyter lab --no-browser --allow-root
