run:
	bash build_start_geos627_container.sh 2>&1 | tee log

clean:
	rm -rf home/.cache home/.conda home/.config home/.empty \
		home/.ipython home/.jupyter home/insar_analysis home/.ipynb_checkpoints \
		home/.local/bin home/.local/lib home/.local/share home/.local/etc \
		home/.local/envs/inverse home/.local/envs/.conda_envs_dir_test