FROM jupyter/base-notebook@sha256:8635b39569cddecf2fac3d95ffe7777d007153e46d47a5dc873357d7cb2d5478

LABEL organization="Alaska Satellite Facility"
LABEL author="Alex Lewandowski, Rui Kawahara, & Eric Lundell"
LABEL creation_date="2021-08-27"

USER root

RUN apt update && \
    apt install --no-install-recommends -y \
        software-properties-common \
        git && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt update && \
    apt upgrade -y

RUN apt update && \
    apt install --no-install-recommends -y \
        zip \
        unzip \
        wget \
        vim \
        rsync \
        less \
        snaphu \
        openssh-client \
        libgl1-mesa-glx \
        emacs \
        gnupg2 \
        jq \
        gfortran \
        proj-bin \
        geotiff-bin \
        libshp-dev \
        libshp2 \
        libhdf5-dev \
        libnetcdf-dev \
        libgdal-dev \
        libgsl-dev \
        curl

ENV UNAVCO_FILES /etc/unavco

RUN mkdir $UNAVCO_FILES && \
    conda install -c conda-forge jupyter_contrib_nbextensions \
      jupyter_nbextensions_configurator \
      jupyter-resource-usage conda-pack \
      kernda \
      nb_conda_kernels

RUN chmod -R 777 /etc/unavco/

COPY etc/pull.py ${UNAVCO_FILES}/pull.py
COPY etc/startup.sh ${UNAVCO_FILES}/startup.sh
COPY etc/install_unavco_pkgs.sh ${UNAVCO_FILES}/install_unavco_pkgs.sh
COPY etc/00-df.py ${UNAVCO_FILES}/00-df.py

USER jovyan

EXPOSE 8888

ENTRYPOINT bash ${UNAVCO_FILES}/startup.sh; jupyter notebook --no-browser --allow-root
